apiVersion: v1
kind: Service
metadata:
  name: {{ include "daemon-substrate-test.fullname" . }}-orchestrator
  labels:
    {{- include "daemon-substrate-test.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
spec:
  type: ClusterIP
  selector:
    {{- include "daemon-substrate-test.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
  ports:
    - name: http
      port: {{ .Values.orchestrator.service.port }}
      targetPort: http

